import { Footer } from '@/components/share/Footer';
import './globals.css';
import { Header } from '@/components/share/Header';

import { UIProvider } from '@/context/ui';

export const metadata = {
  title: 'Next.js learn',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html style={{ height: '100%', background: '#f0f0f0' }} lang='ru'>
      <body
        style={{
          minHeight: '100%',
          display: 'flex',
          flexDirection: 'column',
          margin: 0,
          position: 'relative',
        }}
      >
        <UIProvider>
          <Header />
          <div style={{ flexGrow: 1 }}>{children}</div>
          <Footer />
        </UIProvider>
      </body>
    </html>
  );
}
